### ISSUE TITLE
Undefined Index: x3x Error

### ISSUE THREAD

**Issue by metude** [nazar-pc/php-markdown-next#6]
```
Bla bla = ([`last id - first id`]/range)+1
```

This returns

![asd](http://i.imgur.com/Z6SgFJF.png)

**Comment by nazar-pc** [comment]
I'll look at this today

**Comment by nazar-pc** [comment]
Please, check latest git version if it works for you and me me know.

**Comment by metude** [comment]
I'll check it tomorrow, and will inform you.

**Comment by metude** [comment]
Yep, it works well.

**Comment by metude** [comment]
Another issue appered. Creates link.

```
<p>Bla bla = (<a href="&lt;code&gt;last id - first id&lt;/code&gt;" title="&lt;code&gt;last id - first id&lt;/code&gt;"><code>last id - first id</code></a>/range)+1</p>
```

http://jsbin.com/ukIzovAM/1

**Comment by nazar-pc** [comment]
What you expected?

**Comment by nazar-pc** [comment]
http://michelf.ca/projects/php-markdown/extra/#spe-attr

> Or if using reference-style links and images, put it at the end of the definition line like this:
> 
> ```
> [link][linkref] or [linkref]  
> ![img][linkref]
> 
> [linkref]: url "optional title" {#id .class}
> ```

`[linkref]` exactly this case, right?

**Comment by metude** [comment]
Of course but I was trying to make this: `Bla bla = ([<code>last id - first id</code>]/range)+1`
Not this: `Bla bla = (<a href="&lt;code&gt;......."><code>last id - first id</code></a>/range)+1`

**Comment by nazar-pc** [comment]
Well, I also do not like such behavior too much as well. Probably, I'll remove such feature in future, but for now I cant because of backward compatibility. It does exactly what is declared.
Hopefully, I'll find time to create autonomous documentation about features of PHP Markdown Next and then change some of them.

As for now all I can recommend you - to inherit class and redefine `doAnchors` by removing last regexp block, it corresponds for such links.
Another option - I can add parameter, that will allow to disable this behavior, but by default will provide current one.

My opinion - library should move in direction of GitHub flavored markup, so, changes will come.

**Comment by metude** [comment]
"My opinion - library should move in direction of GitHub flavored markup, so, changes will come."
Absolutely agree.

But interesthing thing [Parsedown](http://parsedown.org/demo) (and Markdown PHP) renders correctly.

**Comment by nazar-pc** [comment]
Because Markdown (which is one of the projects, based on which this library was made) do not support such syntax, this is the feature of Markdown Extra.
I'll start 3.x branch, hopefully soon (there are a lot of other project I'm involved in, even besides Open Source that are present on GitHub).

This is not actually a bug, so, I'll close this issue, but please follow repository for updates or help me with development)

P.S. Created branch `3.0`
